runtime: php72

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:6Hadbc56goe1icfvdra2u3y80JluPH8554ELOBHdiRw=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
